# all students should keep their github repo name lower case with username prefix
# structures
baseurl: '/hiru'
name: Hiru-Sir
title: Hiru-sir
permalink: /:title/
all_batches: https://poloey.gitlab.io/

# about page
training_type: Top Up IT Training (php)
status: Ongoing
facebook_group: topupuy23
facebook_messenger: 1710131265718158
github: poloey 
trainer: Shibu chandra debnath (polo)
## co-ordinate name can be removed. Since I am not adding her name in about page
coordinator: Farzana Ameen
coordinator_facebook: profile.php?id=100008301132291

# personal
project_status: Ongoing
students_number: 
myfacebook: shibudebpolo
mygithub: polodev

#sass:
#  style: compressed
collections:
  students:
    output: true
    permalink: /students/:title/
  projects:
    output: true
    permalink: /projects/:title/
  notices:
    output: true
    permalink: /notices/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      published: true
      no: 1
      category: php
      tags: [html, css, php, web-design, 'web development']
      repo: 
      download_class: true
      view_on_github: true

    # students
  - scope:
      path: ""
      type: students
    values:
      layout: student
      image: false
      mobile: not given 
      show_mobile: true
      show_assignment: true
      email: available soon
      number: 1
      facebook:
      github:
      email:
      mobile: update soon
      bdskills: g
      cv: true
      template: true
      php: false
      php_mysql: false

  # notices
  - scope:
      path: ""
      type: notices
    values:
      layout: notice
      homepage: false
      number: 1
      published: true
      class: bg-info text-light

  # projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      name: a project
      published: true
      team: []
      number: 1
      status: didn't start yet
      # demo and github link will be full url
      github: https://github.com
      demo:
      about: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam provident, id. Necessitatibus, corporis, odit. Officia maiores facere repellendus voluptates doloremque dicta soluta, mollitia deleniti quos sequi sed aliquid temporibus expedita nostrum obcaecati quo laudantium molestiae reprehenderit, quae ducimus sint eaque illo! Natus quo eos ipsam non earum debitis, tempora quisquam cum. Similique iure quia sit magni vitae, qui aut, nisi modi omnis ex vel? At architecto quae, aperiam necessitatibus excepturi magnam quaerat inventore dignissimos laudantium voluptates ex iste unde placeat quibusdam vel dolor minima earum eligendi, explicabo aut atque quisquam nobis reprehenderit ut. Aliquam error accusantium, ullam ipsum expedita nihil.
      
